### ISSUE TITLE
list index out of range, when running run_lstm_RGB.sh

### ISSUE THREAD

**Issue by sujingwang** [LisaAnne/lisa-caffe-public#10]
I0109 21:59:28.015918 14484 layer_factory.hpp:74] Creating layer data
I0109 21:59:28.592169 14484 net.cpp:84] Creating Layer data
I0109 21:59:28.592234 14484 net.cpp:339] data -> data
I0109 21:59:28.592285 14484 net.cpp:339] data -> label
I0109 21:59:28.592309 14484 net.cpp:339] data -> clip_markers
I0109 21:59:28.592324 14484 net.cpp:113] Setting up data
Traceback (most recent call last):
  File "/home/wangsq/Programes/lisa-caffe-public-lstm_video_deploy/examples/LRCN_activity_recognition/sequence_input_layer.py", line 157, in setup
    video_dict[video]['frames'] = frames[0].split('.')[0] + '.%04d.jpg'
IndexError: list index out of range
terminate called after throwing an instance of 'boost::python::error_already_set'
*** Aborted at 1452347968 (unix time) try "date -d @1452347968" if you are using GNU date ***
PC: @     0x7f04f1687267 (unknown)
*** SIGABRT (@0x3e800003894) received by PID 14484 (TID 0x7f04f2cc2780) from PID 14484; stack trace: ***
    @     0x7f04f16872f0 (unknown)
    @     0x7f04f1687267 (unknown)
    @     0x7f04f1688eca (unknown)
    @     0x7f04f1c9306d (unknown)
    @     0x7f04f1c90ee6 (unknown)
    @     0x7f04f1c90f31 (unknown)
    @     0x7f04f1c91199 (unknown)
    @     0x7f04d4685a4d caffe::PythonLayer<>::LayerSetUp()
    @     0x7f04f25e4ee1 caffe::Net<>::Init()
    @     0x7f04f25e73c2 caffe::Net<>::Net()
    @     0x7f04f25d2074 caffe::Solver<>::InitTrainNet()
    @     0x7f04f25d2597 caffe::Solver<>::Init()
    @     0x7f04f25d2985 caffe::Solver<>::Solver()
    @           0x40e386 caffe::SGDSolver<>::SGDSolver()
    @           0x40e648 caffe::GetSolver<>()
    @           0x407f73 train()
    @           0x406028 main
    @     0x7f04f1672a40 (unknown)
    @           0x406409 _start
    @                0x0 (unknown)
./run_lstm_RGB.sh: line 8: 14484 Aborted                 (core dumped) GLOG_logtostderr=1 $TOOLS/caffe train -solver lstm_solver_RGB.prototxt -weights single_frame_all_layers_hyb_RGB_iter_5000.caffemodel
Done.

**Comment by LisaAnne** [comment]
This error means that you have an incorrect path for the video frames.

**Comment by sujingwang** [comment]
The path for the video frames is ./examples/LRCN_activity_recognition/frames
wangsq@wangsq-PowerEdge-R720:~/Programes/lisa-caffe-public-lstm_video_deploy/examples/LRCN_activity_recognition$ ls frames
ApplyEyeMakeup     CliffDiving         HulaHoop        PlayingPiano        SoccerPenalty
ApplyLipstick      CricketBowling      IceDancing      PlayingSitar        StillRings
Archery            CricketShot         JavelinThrow    PlayingTabla        SumoWrestling
BabyCrawling       CuttingInKitchen    JugglingBalls   PlayingViolin       Surfing
BalanceBeam        Diving              JumpingJack     PoleVault           Swing
BandMarching       Drumming            JumpRope        PommelHorse         TableTennisShot
BaseballPitch      Fencing             Kayaking        PullUps             TaiChi
Basketball         FieldHockeyPenalty  Knitting        Punch               TennisSwing
BasketballDunk     FloorGymnastics     LongJump        PushUps             ThrowDiscus
BenchPress         FrisbeeCatch        Lunges          Rafting             TrampolineJumping
Biking             FrontCrawl          MilitaryParade  RockClimbingIndoor  Typing
Billiards          GolfSwing           Mixing          RopeClimbing        UnevenBars
BlowDryHair        Haircut             MoppingFloor    Rowing              VolleyballSpiking
BlowingCandles     Hammering           Nunchucks       SalsaSpin           WalkingWithDog
BodyWeightSquats   HammerThrow         ParallelBars    ShavingBeard        WallPushups
Bowling            HandstandPushups    PizzaTossing    Shotput             WritingOnBoard
BoxingPunchingBag  HandstandWalking    PlayingCello    SkateBoarding       YoYo
BoxingSpeedBag     HeadMassage         PlayingDaf      Skiing
BreastStroke       HighJump            PlayingDhol     Skijet
BrushingTeeth      HorseRace           PlayingFlute    SkyDiving
CleanAndJerk       HorseRiding         PlayingGuitar   SoccerJuggling
wangsq@wangsq-PowerEdge-R720:~/Programes/lisa-caffe-public-lstm_video_deploy/examples/LRCN_activity_recognition$
