### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by ihaeyong** [LisaAnne/lisa-caffe-public#3]
..

**Comment by LisaAnne** [comment]
Hi!

There was a small issue with template instantiation for "ReadImageToCVMat".
This is fixed; please pull the changes and let me know if you still see
this error.

**Comment by ihaeyong** [comment]
Hi, Lisa, 

 

Thank you for your help.

The build has done successfully ;-)

 

Best Regards, 

 

Haeyong Kang.
